### ISSUE TITLE
Setup instructions are broken in README

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/loam#8]
There is no "requirements.txt" in the loam directory.
`pytest tests` also fails. 

I notice that travis script is just calling './scripts/run_tests.sh'. What is the preferred testing mechanism for Loam?

**Comment by phanrahan** [comment]
Yes, to run the loam tests, run

./scripts/run_tests.sh

We need to do this because we can’t run the tests using different mantle backends
in a single invocation of pytest.

**Comment by leonardt** [comment]
I had a WIP resolution to the requirements.txt issue in https://github.com/phanrahan/loam/pull/3, I'll clean that up and merge it in.

**Comment by leonardt** [comment]
Resolved, added requirements.txt because `pip` seems to be removing support for dependency links, which makes installing magma/mantle from the git repo difficult, we can just revert to using requirements.txt for now.
